using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace GLFW {
    public enum GLFWerror : int {
        NOT_INITIALIZED = GLFW3.GLFW_NOT_INITIALIZED,
        NO_CURRENT_CONTEXT = GLFW3.GLFW_NO_CURRENT_CONTEXT,
        INVALID_ENUM = GLFW3.GLFW_INVALID_ENUM,
        INVALID_VALUE = GLFW3.GLFW_INVALID_VALUE,
        OUT_OF_MEMORY = GLFW3.GLFW_OUT_OF_MEMORY,
        API_UNAVAILABLE = GLFW3.GLFW_API_UNAVAILABLE,
        VERSION_UNAVAILABLE = GLFW3.GLFW_VERSION_UNAVAILABLE,
        PLATFORM_ERROR = GLFW3.GLFW_PLATFORM_ERROR,
        FORMAT_UNAVAILABLE = GLFW3.GLFW_FORMAT_UNAVAILABLE
    }
}
